module.exports.descriptors = [
    'Salmon',
    'Cape',
    'Sipjack',
    'Clownfish',
    'Tetra',
    'Coral',
    'Trout',
    'Salmonid',
    'Stringfish',
    'Puff',
    'Trevally',
    'Marlin',
    'Squid',
    'Octo',
    'Salmon Roe',
    'Cuttlefish',
    'Nautilus',
    'Betta',
    'Flounder',
    'Goldfish',
    'Catfish',
    'Angelfish',
    'Swordfish',
    'Tiger Shark',
    'Sturgeon',
    'Tuna',
    'Mackerel',
    'Guppy',
    'Koi',
    'Piranha',
    'Grouper',
    'Halibut',
    'Herring',
    'Lionfish',
    'Mahi Mahi',
    'Opah',
    'Pike',
    'Quillback',
    'Rockfish',
    'Snapper',
    'Tilapia',
    'Urchin',
    'Viperfish',
    'Wahoo',
    'Tetra',
    'Yellowfin',
    'Zebrafish'
    
]
module.exports.places = [
    'Smoke Yard',
    'Valley',
    'River',
    'Hieghts',
    'Rice Fields',
    'Lake',
    'Pond',
    'Bay',
    'Creek',
    'Falls',
    'Reef',
    'Stadium',
    'Depths',
    'Pier',
    'Docks',
    'Shipyard',
    'Cove',
    'Harbor',
    'Island',
    'Knoll',
    'Lagoon',
    'Mountain',
    'Nexus',
    'Oasis',
    'Plateau',
    'Quarry',
    'Ridge',
    'Savannah',
    'Tundra',
    'Underpass',
    'Vista',
    'Wetlands',
    'Hieghts',
] 